/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Edgar Rios' at '13/04/18 03:44 AM' with Gradle 2.14.1
 *
 * @author Edgar Rios, @date 13/04/18 03:44 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public String echoTrama(String trama) {
    	System.out.println("trama:" + trama);
    	return trama;
    }
}
